import 'package:json_annotation/json_annotation.dart';

part 'business_response.g.dart'; // generated by json_annotation package, do not edi

@JsonSerializable()
class CourseReviewResponse {
  @JsonKey(name: 'id')
  int id;
  @JsonKey(name: 'course_id')
  int courseId;
  @JsonKey(name: 'user_id')
  int userId;
  @JsonKey(name: 'user_name')
  String userName;
  @JsonKey(name: 'content')
  String content;
  @JsonKey(name: 'rating')
  int rating;
  @JsonKey(name: 'review_at')
  DateTime reviewAt;
  @JsonKey(name: 'reply_id')
  int? replyId;
  @JsonKey(name: 'reply')
  String? reply;
  @JsonKey(name: 'reply_at')
  DateTime? replyAt;

  CourseReviewResponse({
    required this.id,
    required this.courseId,
    required this.userId,
    required this.userName,
    required this.content,
    required this.rating,
    required this.reviewAt,
    this.replyId,
    this.reply,
    this.replyAt,
  });

  factory CourseReviewResponse.fromJson(Map<String, dynamic> json) =>
      _$CourseReviewResponseFromJson(json);

  Map<String, dynamic> toJson() => _$CourseReviewResponseToJson(this);
}
